version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres
    container_name: rise-postgres
    environment:
      POSTGRES_USER: francis
      POSTGRES_PASSWORD: password
      POSTGRES_DB: dev
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    restart: unless-stopped

  # Redis
  redis:
    image: redis
    container_name: rise-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    restart: unless-stopped

  # RabbitMQ
  rabbitmq:
    image: rabbitmq:3.12
    container_name: rise-rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5673:5672"   # AMQP port
      - "15673:15672" # Management UI
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    restart: unless-stopped

  # NATS
  nats:
    image: noxecane/nats-js-image:latest
    container_name: rise-nats
    ports:
      - "4222:4222"   # Client connections
      - "8222:8222"   # HTTP monitoring
    command: -js -m 8222
    restart: unless-stopped

volumes:
  postgres_data:
  redis_data:
  rabbitmq_data:

networks:
  default:
    name: rise-network